apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-server.fullname" . }}-myapp
  labels:
  {{- include "sample-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.myapp.replicas }}
  selector:
    matchLabels:
      app: myapp
    {{- include "sample-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: myapp
      {{- include "sample-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.myapp.myapp.image.repository }}:{{ .Values.myapp.myapp.image.tag
          | default .Chart.AppVersion }}
        name: myapp
        ports:
        - containerPort: 8080
        resources: {}