kubernetesClusterDomain: cluster.local
myapp:
  myapp:
    image:
      repository: busybox
      tag: "1.33"
  replicas: 1
service:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
