kubernetesClusterDomain: cluster.local
myapp:
  myapp:
    image:
      repository: nanajanashia/argocd-app
      tag: "1.2"
  replicas: 1
service:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
