kubernetesClusterDomain: cluster.local
myapp:
  myapp:
    image:
      repository: nginx
      tag: "1.19"
  replicas: 1
service:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
